import React from 'react'

export const all_daewas=[
{'dr_zakir_naik': [
{'key': 'OQlknDilzso','title': 'ቁርአን ክዘመናዊ ሳይንሰ ጋር ይጋጫል ወይስ ይስማማል P1 By Dr Zakir Naik Amahric'},{'key': 'fUgubzI8pOI','title': 'ቁርአን ክዘመናዊ ሳይንሰ ጋር ይጋጫል ወይስ ይስማማል P2 By Dr Zakir Naik Amahric'},
{'key': '_JK1tp0N8p8','title': 'ቁርአን ክዘመናዊ ሳይንሰ ጋር ይጋጫል ወይስ ይስማማል P3 By Dr Zakir Naik Amahric'},
{'key': 'SmFOlHGqo-Q', 'title': 'ይህን ያውቃሉ P1 By Dr Zakir Naik (Amahric)'},
{'key': 'HCRcd0anMw0', 'title': 'ይህን ያውቃሉ P2 By Dr Zakir Naik (Amahric)'},
{'key': 'GZnjN47EtSc',
'title': 'እውቀት በ ኢስላም ጥላ ሰር P1 By Dr Zakir Naik (Amahric) Uqet ba islam tila sire'},
{'key': '8zlweI3qmXs',
'title': 'እውቀት በ ኢስላም ጥላ ሰር P2 By Dr Zakir Naik (Amahric) Uqet ba islam tila sire'},
{'key': '4QrlvRsbYjo',
'title': 'QURAN BA TIKURET SINEBE 1 BY DR ZAKIR NAIK ( AMAHRIC )'},
{'key': 'TkBcIWDjnwk',
'title': 'QURAN BA TIKURET SINEBE 2 BY DR ZAKIR NAIK ( AMAHRIC )'},
{'key': 'Xzo2nY8digY',
'title': '3ት ሰዎች ለ 1 ዓላማ Part 1 By Dr Zakir Naik 3 Men 1 Mission Moses Jesus Muhammad (PBUP)'},
{'key': 'JbYXe8mnisg',
'title': '3ት ሰዎች ለ 1 ዓላማ Part 2 By Dr Zakir Naik 3 Men 1 Mission Moses Jesus Muhammad (PBUP)'},
{'key': 'O6ixQQoXg4g',
'title': 'ሶላት የፅድቅ ጎዳና | Part 1 | Salat By Dr Zakir Naik (Amharic'},
{'key': 'BDFwaxbXvIA',
'title': 'ሶላት ጥያቄና መልስ  | Part 2 | Salat Q & A By Dr Zakir Naik (Amharic)'},
{'key': 'OGGjUfoJ-r0',
'title': 'ሶላት ጥያቄና መልስ | Part 3 | Salat Q & A  By Dr Zakir Naik (Amharic)'},
{'key': 'hG7C5-f2QC0',
'title': 'ሶላት ጥያቄና መልስ | Part 4 | Salat Q & A By Dr Zakir Naik (Amharic)'},
{'key': '87PEft-0Ltw',
'title': 'ክርክር ከጋዜጠኞች ጋር Part 1 | Kirkere Ke Gazetengoch gera  | Amharic | By Dr Zakir Naik'},
{'key': 'gxnmlNKxttU',
'title': 'ክርክር ከጋዜጠኞች ጋር Part 2 | Kirkere Ke Gazetengoch gera  | Amharic | By Dr Zakir Naik'},
{'key': 'Tm7fihMDqw8',
'title': 'በነሱ ዉስጥ የኛ ሚና  | Part 1 | Dr Zakir Naik - Ba Nasu West Yegna Mina (Amharic)'},
{'key': 'XcOHpF1hJCk',
'title': 'በነሱ ዉስጥ የኛ ሚና  | Part 2 | Dr Zakir Naik - Ba Nasu West Yegna Mina (Amharic'},
{'key': '3O3TVVczAC0',
'title': 'የሰላም ግዛት Part 1 By Dr Zakir Naik (Amharic) Ye Salam Gizat'},
{'key': 'nfpd6ZrIiHQ',
'title': 'የሰላም ግዛት | Part 2 | የጥያቄና መልስ ክፍለ ጊዜ | Q & A |  By Dr Zakir Naik'},
{'key': 'yUj16d8EGgQ',
'title': 'የምን ማፈር | Part 1 | Ye Min Mafer  | Amharic | By Dr Zakir Naik'},
{'key': 'iBPcJfwJCJg',
'title': 'የምን ማፈር | Part 2 | Ye Min Mafer  | የጥያቄና መልስ ክፍለ ጊዜ | Q & A |  By Dr Zakir Naik'},
{'key': 'bsEMWf_dN2Y',
'title': 'ቁርአን የአሏህ ቃል ነዉን Part 1 By Dr Zakir Naik Amahric'},
{'key': 'XS_NTBHaBFc',
'title': 'ቁርአን የአሏህ ቃል ነዉን Part 2 By Dr Zakir Naik Amahric'},
{'key': 'WSPHug7nLrA',
'title': 'ሙስሊሙ ላይ ማነጣጠር ትኩረት በኢሰላም እና አለም አቀፍ ወንድማማችነት P 1 By Dr Zakir Naik'},
{'key': 'W_UVO3dvxz0',
'title': 'ሙስሊሙ ላይ ማነጣጠር ትኩረት በኢሰላም እና አለም አቀፍ ወንድማማችነት P 2 By Dr Zakir Naik'},
{'key': 'B2bgfDH7S9A',
'title': 'ሰላም የኢስላም ራዕይ  Part 1 By Dr Zakir Naik (Amahric )'},
{'key': 'jwEXFpd8mdk',
'title': 'አሽባሪነትና ጂሀድ ከ እስላማዊ እይታ አኮያ በሚል ርዕስ Part 1 By Dr Zakir Naik Amahric'},
{'key': 'Q8B0Rgg1fVs',
'title': 'አሽባሪነትና ጂሀድ ከ እስላማዊ እይታ አኮያ በሚል ርዕስ Part 2 By Dr Zakir Naik Amahric'},
{'key': 'mZyAxz4rz-A',
'title': 'ምዕራባውያን ለምን ይሆን የሚሰልሙት?  | Part 1 | Why the West Is Coming To Islam ? By Dr Zakir Naik'},
{'key': 'NO6O4G47InM',
'title': 'ምዕራባውያን ለምን ይሆን የሚሰልሙት?  | Part 2 | Why the West Is Coming To Islam ? By Dr Zakir Naik'},
{'key': 'FhF4ncETb7g',
'title': 'ልዩ የጥያቄ እና መልስ ፕሮግራም |  Part 1  | Dr Zakir Naik ( Amaharic'},
{'key': 'TRXgY_KvJaI',
'title': 'ልዩ የጥያቄ እና መልስ ፕሮግራም |  Part 2  | Dr Zakir Naik Amaharic'},
{'key': 'upHbSe5nVBU',
'title': 'ሽሽት | Part 1 | ዶር ዛኪር ናይክ | By Dr. Zakir Naik (Amharic)'},
{'key': '5_f8OANpKBI',
'title': 'ሽሽት | Part 2 | ዶር ዛኪር ናይክ | By Dr.Zakir Naik (Amharic)'},
{'key': 'aa620mCNGvY',
'title': 'ሽሽት | Part 3 | ዶር ዛኪር ናይክ | By Dr.Zakir Naik (Amharic)'},
{'key': 'fb9PRQ2L-50',
'title': 'ኢስላም መካከለኛዉ መንገድ | Part 1 | Dr Zakir Naik - Islam The Middle Path (Amharic)'},
{'key': '8owNVDNYmaE',
'title': 'ኢስላም መካከለኛዉ መንገድ | Part 2 | Dr Zakir Naik - Islam The Middle Path (Amharic)'},
{'key': 'u04Kpk6d2Ck',
'title': 'በቁርአን የታወጀዉ ከወለድ ነፃ ኢኮኖሚ | Part 1 | Dr. Zakir Naik - Interest Free Economy Promulgated by Quran'},
{'key': 'mwdxD2NK6k0',
'title': 'በቁርአን የታወጀዉ ከወለድ ነፃ ኢኮኖሚ | Part 2 | Dr. Zakir Naik - Interest Free Economy Promulgated by Quran'},
{'key': 'NIfYeLBiLuI',
'title': 'lemendew yatfarkut 2 BY DR ZAKIR NAIK ( AMAHRIC )'},
{'key': 'bIdP4a5STZw', 'title': 'የጀነት ቁልፍ P1 By Dr Zakir Naik ( Amahric )'},
{'key': 'RNjr4SMiF3g', 'title': 'የጀነት ቁልፍ P2 By Dr Zakir Naik ( Amahric )'},
{'key': 'dsCBcWYglNM',
'title': 'የጀነት ቁልፍ P 3 By Dr Zakir Naik ( Amahric )'},
{'key': 'V0dP3CYSjc8', 'title': 'የሂዎት አላማ P 1 Dr Zakir Naik ( Amahric )'},
{'key': 'GCr3e_HaHXQ', 'title': 'የሂዎት አላማ P 2 Dr Zakir Naik ( Amahric )'}],
'ustaz_abuhayder': [{'key': 'uFCbis2Aldw',
'title': 'እውን ኢየሱስ አምላክ ነውን?  Is Jesus God ? Ustaz AbuHyder Debate With Bereket (Amharic)'},
{'key': '5QKySAr3qyI',
'title': 'እውን ኢየሱስ አምላክ ነውን? Is Jesus God ? Part 1 Ustaz Abu Heydar Debate With Postor George (Amharic)'},
{'key': 'jI6cHYGdBH8',
'title': 'እውን ኢየሱስ አምላክ ነውን? Is Jesus God ? Part 2 Ustaz Abu Heydar Debate With Postor George (Amharic)'},
{'key': 'tHSbyq6A71Q',
'title': 'እየሱስ በቁርአንና በወንጌል | P 1 | ዳኢ ሳዲቅ ሙሓመድ | Jesus In Quran & Bible'},
{'key': 'OdVhDRl-6Io',
'title': 'እየሱስ በቁርአንና በወንጌል | P 2 | ዳኢ ሳዲቅ ሙሓመድ | Jesus In Quran & Bible'},
{'key': 'gTquRRACres',
'title': 'እየሱስ በቁርአንና በወንጌል | P 3 | ዳኢ ሳዲቅ ሙሓመድ | Jesus In Quran & Bible'},
{'key': 'kDzUXVzOdKs',
'title': 'እየሱስ በቁርአንና በወንጌል | P 4 | ዳኢ ሳዲቅ ሙሓመድ | Jesus In Quran & Bible'},
{'key': 'Rlpo4SKpPM4',
'title': 'የኢማን መሰረቶች | Part 1 | ዳኢ ሳዲቅ ሙሓመድ | Ye Iman Mesaretoch By Dai Sadiq Mohammed'},
{'key': 'Pijs5v0TSA0',
'title': 'የኢማን መሰረቶች | Part 2 | ዳኢ ሳዲቅ ሙሓመድ | Ye Iman Mesaretoch By Dai Sadiq Mohammed'},
{'key': 'kFheWdJtfDo',
'title': 'የኢማን መሰረቶች | Part 3 | ዳኢ ሳዲቅ ሙሓመድ | Ye Iman Mesaretoch By Dai Sadiq Mohammed'},
{'key': 'zcTBrgKbqyU',
'title': 'የኢማን መሰረቶች | Part 4 | ዳኢ ሳዲቅ ሙሓመድ | Ye Iman Mesaretoch By Dai Sadiq Mohammed'},
{'key': 'Fkp9WHR9-Qo',
'title': '2 የዕምነት ማዕዘናት በ By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'rOEbFnSLaKo',
'title': '3 በአላህ ማመን ክፍል 1 በ By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'lkqk_7Kz3Yc',
'title': '4 በአላህ ማመን ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'Nfjw9BXc9Gc',
'title': '5 በአላህ ማመን ክፍል 3 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'ONjBi669emE',
'title': '6 በአላህ ማመን ክፍል 4 በ By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '7AJKz4KekkM',
'title': '7  በነቢያት ማመን By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'pxsWD72WuTE',
'title': '8  ከኢስላም ማዕዘናት (ሸሃዳህ)  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'kQl_crcwfzQ',
'title': '9  (Taqwa)  አላህን መፍራት  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'jGLr3ftIk_4',
'title': '10 ልብን ማስተካከል  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'nN2g5JOFROg',
'title': '11 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'ewJ69QwkJys',
'title': '12 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '1uNz6i-rKZk',
'title': '13 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 3 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '7T1IJi5Afmk',
'title': '14 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 4 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '_KZqQl_ZQfc',
'title': '15 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 5 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'ygQcTQw0NKU',
'title': '16 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 6 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'aP29F9xFT-8',
'title': '17 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 7 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'koAT_19WW5s',
'title': '18 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 8 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'CsS-3kEpA1A',
'title': '19 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 9 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'iyxslgjISBY',
'title': '20 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 10 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'PPPd61VfKzg',
'title': '21 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል 11 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '5dyG3_WXIlo',
'title': '22 ዒሳ (ዐ.ሰ) በቁርአንና በወንጌል ክፍል By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'tppe-ryPtHs',
'title': '23 እውን ዒሳ (ዐ.ሰ) ተሰቅሎ ነበርን? By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'iLGr8m5QQqc',
'title': '24  ፀፀት By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'sZhfRI9hCnY',
'title': '25 የሶላት አስፈላጊነት በኢስላም By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'sax3_ZnYQW8',
'title': '26 የነቢዩላህ አደም (ዐ ሰ) ታሪክ ክፍል1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'WEDaFWrRAH4',
'title': '27 የነቢዩላህ አደም ታሪክ ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'tIfX3HlCSrE',
'title': '28 የቅዱስ ቁርኣን ምንነት By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'gthlOH-kVV8',
'title': '29 አላህ ሁሉን ዐዋቂ ነው!  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'bsdipXaem6M',
'title': '30 የሙስሊም ስነ-ምግባር ክፍል 1  By Dai Sadiq Mohammed ( Ustaz Abu Heydar ))'},
{'key': 'wGP14VWfpIw',
'title': '31 የሙስሊም ስነ-ምግባር ክፍል 2  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'RmhdOYYfdn4',
'title': '32 የነቢዩ ሙሐመድ (ሰ.ዓ.ወ) ማንነት ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'IHZ5WWHJsC8',
'title': '33 የነቢዩ ሙሐመድ ማንነት (ሰ.ዓ.ወ) ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '5RsIqWBRhSg',
'title': '34 የነቢዩ ሙሐመድ (ሰ.ዓ.ወ)  ማንነት ክፍል 3 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '0slVlkBLhvk',
'title': '35 ቀዷ ወል-ቀደር በኢስላም ከፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'Djt7cRkP_-g',
'title': '36 ቀዷ ወል-ቀደር በኢስላም ከፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'Wjt2499Pd3c',
'title': '37 ቀዷ ወል-ቀደር በኢስላም ከፍል 3 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'nyLP_3NOe3c',
'title': '38 ቀዷ ወል-ቀደር በክርስትና ከፍል 4 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'l6YFqkYwBgw',
'title': '39 ዒሳ (ዐ.ሰ) እንዴት ተፈጠረ? ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'dFvlPLNyzmE',
'title': '40 የዒሳ (ዐ.ሰ)  ተአምራቶች ክፍል 2  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '4Vgb0CQqlv0',
'title': '41 እውን ዒሳ (ዐ.ሰ) የአላህ ልጅ ነው ወይስ ባሪያ? ክፍል 3 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '4ypLuEvn4-8',
'title': '42 ዒሳ (ዐ.ሰ)  ነቢይ ነበርን ወይስ ከነቢይ በላይ? ክፍል 4 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'XeBHgZqxDyE',
'title': '43 የዒሳ (ዐ.ሰ)  አስተምህሮ ምን ነበር? ክፍል 5  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'LbFhMXNqcBo',
'title': '44 እውን ዒሳ (ዐ.ሰ)  አምላካዊ ባሕሪ ነበረውን? ክፍል By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'R1MVaYpNF-c',
'title': '45 እውን ዒሳ (ዐ.ሰ)  አምላካዊ ባሕሪ ነበረውን? ክፍል 7 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'btU_kVZUUyU',
'title': '46 እውን ዒሳ (ዐ.ሰ)  አምላካዊ ባሕሪ ነበረውን? ክፍል 8  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'vlEJsm5G_sg',
'title': '47 እውን ዒሳ (ዐ.ሰ)  ተሰቅሎ ነበርን? ክፍል 9 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'ebLs8k7Ay5o',
'title': '48 እውን ዒሳ (ዐ.ሰ) ተሰቅሎ ነበርን? ክፍል 10 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'x4hIJSITxBw',
'title': '49 መንፈሳዊው ዓለም ምንድነው? By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '6C0nDJuM4kE',
'title': '50 ጀነትና ጀሐነም በኢስላም By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'P9AwtTnh-Qs',
'title': '51. የነቢዩ ሙሐመድ (ሰ.ዓ.ወ) ልዩ መለያዎች  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'QnMUdxApw8I',
'title': '52 አደምና ሀዋ   By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'PLFFO4P0zOg',
'title': '53  ሱንና(ሐዲሥ) ምንድነው?  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'd2L2BAjCuMQ',
'title': '54 ኢስላምን ያለ ሐዲሥ መተግበር እንዴት? By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'QPvwnLgZiwM',
'title': '55  የጀነት መንገድ By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'MgZDIo7-egM',
'title': '56 ልብን ማስተካከል  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '9YHsDIQFzRk',
'title': '57 ጀነት በኢስላም By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'Ks2Tnvf70Uc',
'title': '58.ፍቅር በኢስላም ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'n99pbbG_r5I',
'title': '59 ፍቅር በኢስላም ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'aKkwq06PW9Y',
'title': '60። በመላእክት ማመን ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'PURwjeer0mY',
'title': '61። በመላእክት ማመን ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'XKKaD-Ri35k',
'title': '62። ጂኒዎችና የሸይጣናት ዓለም By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '6zPjetfi6Hk',
'title': '63። እምነት ምንድነው? ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'ClSHipPCzyk',
'title': '64። እምነት ምንድነው ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'c-oXN-w1-OE',
'title': '65። አላህንና መልክተኛውን መታዘዝ By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'D4HvcsF9eJg',
'title': '66። የአላህ ዘጠና ዘጠኝ ስሞች ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'PjYeHIPHK6o',
'title': '67። የኢስላማዊው እምነት መለያ ባሕርያት ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'cMqtONKrN2o',
'title': '68። የኢስላማዊው እምነት መለያ ባሕርያት ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'I58JyiwEzTs',
'title': '69። የኢስላማዊው እምነት መለያ ባሕርያት ክፍል 3 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'n0Lxnkujkg0',
'title': '70። የመናፍቃን ባሕሪይ By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '1RgV_4uOYCE',
'title': '71። ዱዓ በኢስላም By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'emgeAsiH9Wg',
'title': '72። ፆም በኢስላም ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '52NHZcqKlfU',
'title': '73። ፆም በኢስላም ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'pTyWM0MkxSs',
'title': '74። በ ፈጣሪ ማመን ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '7efA0Z9oHYQ',
'title': '75። በ ፈጣሪ ማመን ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'iJjhPrBLnIY',
'title': '76። በፈጣሪ ማመን ክፍል 3 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'c50oapzUkAo',
'title': '77። በፈጣሪ ማመን ክፍል 4 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'EPkZJmggkxc',
'title': '78። በፈጣሪ ማመን ክፍል 5 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'zoibaUM7Kdg',
'title': '79። አላህ ማነው? ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'uD-dySbqSbs',
'title': '80። አላህ ማነው? ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'DPZsOD_03D0',
'title': '81። አላህ ማነው? ክፍል 3 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'AcP4r5qQ1c8',
'title': '82። አላህ ማነው? ክፍል 4 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'GfyQ478iCYA',
'title': '83. ሞት በኃጢአት ምክንያት የመጣ ነውን? By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'VeQO09CN53Y',
'title': '84. የኤፍታህ መፅሄት ቅሌት ክፍል አንድ By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'zFIaGzb6gPg',
'title': '85. የኤፍታህ መፅሄት ቅሌት ክፍል ሁለት By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '-3kqxDNFoDQ',
'title': '86 Ustaz Abu Heyder - The Need For Interfaith Dialogue'},
{'key': 'yxF_w7aq9tg',
'title': '87. ጥያቄና መልስ ክፍል አንድ1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'lCI0k4f9Z_I',
'title': '88. ጥያቄና መልስ ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '56qeYngyjto',
'title': '89. እምነትና ክህደት በኢስላም ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '9ZzhY5jSSU4',
'title': '90. እምነትና ክህደት በኢስላም ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'rjKbvu5qZNc',
'title': '91. እምነትና ክህደት በኢስላም ክፍል 3 Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '7kOPAi5N7U4',
'title': '92.ልብን ማስተካከል ክፍል 1 Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '1abUwq06AWo',
'title': '93. ልብን ማስተካከል ክፍል 2 Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'LvWDiTaNOP0',
'title': '94. የሱረቱል ፋቲሐ መልእክት  Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'hpCStLIBSMs',
'title': '95. የነቢዩ ሙሐመድ (ሰ.ዓ.ወ) ተአምራት በከፊል Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'QCDSHuuxDo4',
'title': '96.በመለኮታዊ መጻህፍት ማመን ክፍል 1  Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'lSjaHrT3lMU',
'title': '97.በመለኮታዊ መጻህፍት ማመን ክፍል 2  Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'AXO2JGkIito',
'title': '98. የቅዱስ ቁርኣን ስሞችና ባሕሪያት  Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'mh-kEQmWjMw',
'title': '99. የሶብር ምንነት በኢስላም By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'XVnUnWMoOC4',
'title': '100.የአላህ ስሞችና ባሕሪያት ክፍል አንድ  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'FkxthKnsfbs',
'title': '101.የአላህ ስሞችና ባሕርያት ክፍል ሁለት By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'h4EUeXbdWZc',
'title': '102. ተውሒድ በኢስላም By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '46AsWwNyXUw',
'title': '103. የሽርክ አስከፊነት በኢስላም By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '3FrY9itqNZA',
'title': '104. ከሞት በኋላ ህይወት ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'CUJxKlwKba8',
'title': '105. ከሞት በኋላ ህይወት ክፍል 2 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'NhRlw3Nwwzk',
'title': '106. ከሞት በኋላ ህይወት ክፍል 3 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'oLdff7sWhH4',
'title': '107. ከሞት በኋላ ህይወት ክፍል 4 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'uy7uSuXKI10',
'title': '108. ከሞት በኋላ ህይወት ክፍል 5 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '0Lf507_GHBk',
'title': '109. መላእክትና ጂን በኢስላም ክፍል 1 By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'UQo6Yu6dQ-k',
'title': '110. መላእክትና ጂን በኢስላም ክፍል ሁለት  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'z0cfaWEAQ-E',
'title': '111.ነቢያት ሁሉ ሙስሊም ነበሩ  By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'u5gDb-E4mUc',
'title': '112. ይቅርታና ምሕረት በኢስላም By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': '30dSyajF9Wc',
'title': '113 . ጂኒዎች ምንድናቸው? By Dai Sadiq Mohammed ( Ustaz Abu Heydar )'},
{'key': 'oatl-Ej0DZE',
'title': 'Ya La ILaha ILalah  Magbiya Part 1 Ustaz Sadik Mohammed (Abu Heyder )'},
{'key': 'qwn-pdJCjPc',
'title': 'Ya La ILaha ILalah  Magbiya Part 2 Ustaz Sadik Mohammed (Abu Heyder )'},
{'key': 'cDYrQ-IMJ4I',
'title': 'Ya La ILaha ILalah  Magbiya Part 3 Ustaz Sadik Mohammed (Abu Heyder )የ'},
{'key': 'tr9RErQ3Ul0',
'title': 'Ya La ILaha ILalah  Magbiya Part 4 Ustaz Sadik Mohammed (Abu Heyder )'},
{'key': 'w06VIYNxEyo',
'title': 'Ya La ILaha ILalah Magbiya Part 5 Ustaz Sadik Mohammed (Abu Heyder )'},
{'key': 'Oz9z2wZatgE',
'title': 'Ya Ibada Magbiya Part 1 Ustaz Sadik Mohammed (Abu Heyder )'},
{'key': 'irGvpCPLHao',
'title': 'አዎ ሶስት አይደለም ምንም እኛ ቢልም Ustaz Sadik Mohammed (Abu Heyder )'},
{'key': 'jptQ0T_FuwY',
'title': 'የ ኢስላም መልእክት ‹‹ላኢላሀ ኢልለሏህ›› አንድ አምላክ እና አንድ አምልኮ ክፍል 1 በ ዳኢ ሳዲቅ ሙሓመድ'},
{'key': 'VeTVie81a_o',
'title': 'የ ኢስላም መልእክት ‹‹ላኢላሀ ኢልለሏህ›› አንድ አምላክ እና አንድ አምልኮ ክፍል 2 በ ዳኢ ሳዲቅ ሙሓመድ'},
{'key': 'dMAtL_ul-bk',
'title': 'የ ኢስላም መልእክት ‹‹ላኢላሀ ኢልለሏህ›› አንድ አምላክ እና አንድ አምልኮ ክፍል 3 በ ዳኢ ሳዲቅ ሙሓመድ'},
{'key': 'rU28M8KBlfI',
'title': 'የነበዩ (ሰ.ዓ.ወ) ማንነት በ ዳኢ ሳዲቅ ሙሓመድ By Dai Sadiq Mohammed'},
{'key': 'Cl-RKJ9Ysps',
'title': 'ታላቅ ፍጥጫ || በኡስታዝ አቡ ሀይደር እና ተክሉ ተመስገን || The Big Debate || USTAZ ABU HEYDER & TEKLU TEMESGEN'},
{'key': 'HAAycOOMJWE',
'title': 'Ustaz Abu Heydar - Al Usulu Salasa P1  (አል-ዑሱሉ አል-ሰላላህ)'},
{'key': 'CkNfHsXxE58',
'title': 'Ustaz Abu Heydar - Al Usulu Salasa P2  (አል-ዑሱሉ አል-ሰላላህ)'},
{'key': 'ntebTuSVL98',
'title': 'Ustaz Abu Heydar - Al Usulu Salasa P 3  (አል-ዑሱሉ አል-ሰላላህ)'},
{'key': 'I5RYn-KFtgk',
'title': 'Ustaz Abu Heydar - Al Usulu Salasa P4 (አል-ዑሱሉ አል-ሰላላህ)'},
{'key': 'LRtOCE8hdk4',
'title': 'Ustaz Abu Heydar - Al Usulu Salasa P5 (አል-ዑሱሉ አል-ሰላላህ)'},
{'key': 'SCeMNHMMOe4',
'title': 'Ustaz Abu Heydar - Al Usulu Salasa P6 (አል-ዑሱሉ አል-ሰላላህ)'},
{'key': 'SPQFclk_8m0',
'title': 'Ustaz Abu Heydar - Al Usulu Salasa P7 (አል-ዑሱሉ አል-ሰላላህ)'},
{'key': 'AH7cIx53Csw',
'title': 'Ustaz Abu Heydar - Al Usulu Salasa P8 (አል-ዑሱሉ አል-ሰላላህ)'},
{'key': 'L1ir7jyhWkg',
'title': 'Ustaz Abu Heydar - Al Usulu Salasa P9 (አል-ዑሱሉ አል-ሰላላህ)'},
{'key': 'qckJLOCJYfQ',
'title': 'Ustaz Abu Heydar - Al Usulu Salasa P10 (አል-ዑሱሉ አል-ሰላላህ) አሥር የመጨረሻ ክፍል'},
{'key': 'DzXexOxMbxw',
'title': 'Ustaz Abu Heydar - ላ ኢላሀ ኢልለሏህ  አስፈላጊነቱ!  P1 በኡስታዝ አቡ ሀይደር'},
{'key': 'G7xK1aXijUE',
'title': 'Ustaz Abu Heydar - ላ ኢላሀ ኢልለሏህ :– ትርጉሙ P2 በኡስታዝ አቡ ሀይደር'},
{'key': 's9ccFXRASdc',
'title': 'Ustaz Abu Heydar ከሞት በኋላ ሕይወት P1 ኡስታዝ አቡ ሀይደር'},
{'key': '2ElTD7ttCVg',
'title': 'Ustaz Abu Heydar  ከሞት በኋላ ሕይወት P2 ሞት እና በርዘኽ'},
{'key': '2z794tD40bo',
'title': 'Ustaz Abu Heydar  ከሞት በኋላ ሕይወት P3 – መቀስቀስ መኖሩን ማን አረጋገጠ'},
{'key': 'imBhO1_4YgU',
'title': 'Ustaz Abu Heydar  ከሞት በኋላ ሕይወት P4 – መሰብሰብ'},
{'key': 'B06TunAkMrw',
'title': 'Ustaz Abu Heydar  ከሞት በኋላ ሕይወት P5 – ሐውድ እና ሸፋዐህ'},
{'key': 'darVN43Zu0M',
'title': 'Ustaz Abu Heydar  ከሞት በኋላ ሕይወት P6 – አል ሒሳብ ምርመራ'},
{'key': 'rvfyvEhQXPU',
'title': 'Ustaz Abu Heydar  ከሞት  በኋላ ሕይወት P7 – ሲራጥ ጀነት እና ጀሀነም'},
{'key': 'ndIBOiPOujM',
'title': 'Ustaz Abu Heydar  ከሞት በኋላ ሕይወት P8 – የጀነት ጸጋዎች 1 መንፈሳዊ ጸጋዎች'},
{'key': 'SV8p0wdCUds',
'title': 'Ustaz Abu Heydar  ከሞት በኋላ ሕይወት P9 – የጀነት ጸጋዎች 2 ስጋዊ ጸጋዎች'},
{'key': 'iXhll9Iviq4',
'title': 'Ustaz Abu Heydar ከሞት በኋላ ሕይወት P10 – ጀነት የመግቢያ ምክንያቶች የመጨረሻ ክፍል'},
{'key': 'hBW3R-jMEP4', 'title': 'Ustaz Abu Heydar  በነቢያት ማመን P1'},
{'key': 'Fw2aVPywQgw', 'title': 'Ustaz AbuHeydar  በነቢያት ማመን P2'},
{'key': 'KPCvKKuZ4JE', 'title': 'Ustaz Abu Heydar  በነቢያት ማመን P3'},
{'key': 'vOhIO28UF9I', 'title': 'Ustaz AbuHeydar  በነቢያት ማመን P4'},
{'key': 'H1OnpheQuV4', 'title': 'Ustaz AbuHeydar  በነቢያት ማመን P5 የነቢያት ተአምር'},
{'key': 'vt-NjK7lQFg',
'title': 'Ustaz Abu Heydar በነቢያት ማመን P6 የረሱል ሐቅ በኛ ላይ'},
{'key': '2cPOf6hNNfg',
'title': 'Ustaz Abu Heydar  ሹሩጡ–ሶላህ P1 የሶላት ቅድመ ዝግጅቶች'},
{'key': 'aScJDZU1Rdk',
'title': 'Ustaz Abu Heydar  ሹሩጡ–ሶላህ P2 የሶላት ቅድመ ዝግጅቶች'},
{'key': 'pU8nqR1Lc8A',
'title': 'Ustaz Abu Heydar  ሹሩጡ–ሶላህ P3 የሶላት ቅድመ ዝግጅቶች'},
{'key': 'LUxQs9Xh79k', 'title': 'Ustaz Abu Heydar  አርካኑ–ሶላህ P4 የሶላት ማእዘናት'},
{'key': 'mLFNpv_x90o',
'title': 'Ustaz Abu Heydar  አርካኑ–ሶላህ P5 የሶላት ማእዘናት P5'},
{'key': 'w-pbnncX-Jo', 'title': 'Ustaz Abu Heydar አርካኑ–ሶላህ P6 የሶላት ማእዘናት'},
{'key': 'DRW0CbedSGA', 'title': 'Ustaz Abu Heydar  አርካኑ–ሶላህ P7 የሶላት ዋጂቦች'},
{'key': 'lseN3BS4Nc0', 'title': 'Ustaz Abu Heydar  ሱነኑ–ሶላህ P8 የሶላት ሱንናዎች'},
{'key': 'GgaFhyshCUU',
'title': 'Ustaz Abu Heydar  ሙብጢላቱ ሶላህ ወመክሩሃቲሃ P9 ሶላትን የሚያፈርሱና የተጠሉ ነገራት'},
{'key': 'uuXzm8A_S3w', 'title': 'Ustaz Abu Heydar ሱጁደ ሰህው P10 የመርሳት ሱጁድ'},
{'key': 'xEmoo__4F3Y',
'title': 'Ustaz Abu Heydar ሱጁደ ሰህው P11 የመርሳት ሱጁድ ከባለፈው የቀጠለ'},
{'key': 'mPXuzJ2MuRE',
'title': 'Ustaz Abu Heydar ወስዋስ በዒባዳ ላይ አስቸገረኝ! መፍትሄውስ P12'},
{'key': 'o1nWP1la7bs', 'title': 'Ustaz Abu Heydar  በቀዷ ወል–ቀደር ማመን P1'},
{'key': 'VwF3v5lhcpY', 'title': 'Ustaz Abu Heydar  በቀዷ ወል–ቀደር ማመን P2'},
{'key': 'Qzo-cF0Y3tg', 'title': 'Ustaz Abu Heydar  በቀዷ ወል–ቀደር ማመን P3'},
{'key': 'DKIch8Xo7tY',
'title': 'Ustaz Abu Heydar  በቀዷ ወል–ቀደር ማመን P4 "በቀደር የማመን ጥቅሞች"'},
{'key': 'WSaXa-aQp0E', 'title': 'Ustaz Abu Heydar  በቀዷ ወል–ቀደር ማመን P5'},
{'key': 'mbvrd2DmFlw', 'title': 'Ustaz Abu Heydar   በቀዷ ወል–ቀደር ማመን P6'},
{'key': 'GBfa9ga4JkM',
'title': 'Ustaz Abu Heydar በቀዷ ወል–ቀደር ማመን P7 "መምራትና ማጥመም"'},
{'key': 'gMCZWf8SIqA',
'title': 'Ustaz Abu Heydar  በቀዷ ወል–ቀደር ማመን P8 "የአላህ ፍትሐዊነት"'},
{'key': 'VcN7mXeUQ_k',
'title': 'Ustaz Abu Heydar በመላእክት ማመን P7 የመላእክት የሥራ ድርሻ መላእክትና የመጨረሻው ቀን'},
{'key': 'J6jgLacSDUI',
'title': 'Ustaz Abu Heydar በመላእክት ማመን P8 በመላእክት የማመን ፍሬ'},
{'key': 'smkNU1OoYZ0',
'title': 'Ustaz Abu Heydar  በመላእክት ማመን P6 የመላእክት የሥራ ድርሻ መላእክትና ሙስሊሞ'},
{'key': 'RVRMrZnjLeo',
'title': 'Ustaz AbuHeydar በመላእክት ማመን P5 የመላእክት የሥራ ድርሻ'},
{'key': '8nsVV_YRwKE',
'title': 'Ustaz Abu Heydar  በመላእክት ማመን P4 የመላእክት የሥራ ድርሻ'},
{'key': 'q8SP7kbxJxE',
'title': 'Ustaz Abu Heydar በመላእክት ማመን P3 የመላእክት ስነ–ምግባራዊ ማንነት'},
{'key': 'U07jSDkzYzM',
'title': 'Ustaz Abu Heydar በመላእክት ማመን P2 የመላእክት ተፈጥሮአዊ ማንነት'},
{'key': 'HKkF66rZ_pE',
'title': 'Ustaz Abu Heydar በመላእክት ማመን P1 የመላእክት ተፈጥሮአዊ ማንነት'},
{'key': 'BHEk385auFE',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P1 ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'xPMlQqyMWWU',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P2 ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'vwHqPYRQFK4',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P3  ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'cSZ2rCoeQgA',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P4 ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'TlLpGa__rzs',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P5 ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'BlHvHvZnbL0',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P6 ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'bqKZn1LpBLE',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P13  ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': '6dXEqBAmLuA',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P8 ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'WMCFAZcbRHk',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P9 ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'xry_FCleblQ',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P10 ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'tFMhPmWmwrQ',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P15  ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'h12mGCJTrc0',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P14  ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'FIzx3kzoxJM',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P12 ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'},
{'key': 'YikcKoHSEb0',
'title': 'Ustaz Abu Heydar   Kitab al Tawhid P11  ኡስታዝ አቡ ሀይደር  ኪታቡ ተውሂድ'}],
'shekh_mohamed_hamidin': [{'key': 'PVQM5PYRK2M',
'title': 'ሲራ ክፍል 1 በ ሼኽ መሀመድ ሃሚዲን Siira 1 Amharic By Shek Mohammed Hamidin'},
{'key': 'xxuojhZas0w',
'title': 'ሲራ ክፍል 2 በ ሼኽ መሀመድ ሃሚዲን Siira 2 Amharic By Shek Mohammed Hamidin'},
{'key': 'RO9aOASBLUo',
'title': 'ሲራ ክፍል 3 በ ሼኽ መሀመድ ሃሚዲን Siira 3 Amharic By Shek Mohammed Hamidin'},
{'key': 'A7F0npbtQ8k',
'title': 'ሲራ ክፍል 4 በ ሼኽ መሀመድ ሃሚዲን Siira 4 Amharic By Shek Mohammed Hamidin'},
{'key': 'IKv6eBbSGKY',
'title': 'ሲራ ክፍል 5 በ ሼኽ መሀመድ ሃሚዲን Siira 5 Amharic By Shek Mohammed Hamidin'},
{'key': 'TNa4FehCpPo',
'title': 'ሲራ ክፍል 6 በ ሼኽ መሀመድ ሃሚዲን Siira 6 Amharic By Shek Mohammed Hamidin'},
{'key': 'icnBoAy1E68',
'title': 'ሲራ ክፍል 7 በ ሼኽ መሀመድ ሃሚዲን Siira 7 Amharic By Shek Mohammed Hamidin'},
{'key': '_-nIH-mU3E4',
'title': 'ሲራ ክፍል 8 በ ሼኽ መሀመድ ሃሚዲን Siira 8 Amharic By Shek Mohammed Hamidin'},
{'key': 'mNRQrVHiheI',
'title': 'ሲራ ክፍል 9 በ ሼኽ መሀመድ ሃሚዲን Siira 9 Amharic By Shek Mohammed Hamidin'},
{'key': 'Rgw9I_pSwdw',
'title': 'ሲራ ክፍል 10 በ ሼኽ መሀመድ ሃሚዲን Siira 10 Amharic By Shek Mohammed Hamidin'},
{'key': 'AZ-us_4Q6s4',
'title': 'ሲራ ክፍል 11 በ ሼኽ መሀመድ ሃሚዲን Siira 11 Amharic By Shek Mohammed Hamidin'},
{'key': 'kYv8knoMdJk',
'title': 'ሲራ ክፍል 12 በ ሼኽ መሀመድ ሃሚዲን Siira 12 Amharic By Shek Mohammed Hamidin'},
{'key': 'YYv3wayz04M',
'title': 'ሲራ ክፍል 13 በ ሼኽ መሀመድ ሃሚዲን Siira 13 Amharic By Shek Mohammed Hamidin'},
{'key': 'VkGQu-NcAcs',
'title': 'ሲራ ክፍል 14 በ ሼኽ መሀመድ ሃሚዲን Siira 14 Amharic By Shek Mohammed Hamidin'},
{'key': 'yj-ZaktkM6M',
'title': 'ሲራ ክፍል 15 በ ሼኽ መሀመድ ሃሚዲን Siira 15 Amharic By Shek Mohammed Hamidin'},
{'key': 'xZaB8VpiD3k',
'title': 'ሲራ ክፍል 16 በ ሼኽ መሀመድ ሃሚዲን Siira 16 Amharic By Shek Mohammed Hamidin'},
{'key': '5fMRwEOP7XE',
'title': 'ሲራ ክፍል 17 በ ሼኽ መሀመድ ሃሚዲን Siira 17 Amharic By Shek Mohammed Hamidin'},
{'key': 'T8DGoQ5-AVM',
'title': 'ሲራ ክፍል 18 በ ሼኽ መሀመድ ሃሚዲን Siira 18 Amharic By Shek Mohammed Hamidin'},
{'key': 'VwLZgbJXsAA',
'title': 'ሲራ ክፍል 19 በ ሼኽ መሀመድ ሃሚዲን Siira 19 Amharic By Shek Mohammed Hamidin'},
{'key': 'HVvBZZ7Q9uM',
'title': 'ሲራ ክፍል 20 በ ሼኽ መሀመድ ሃሚዲን Siira 20 Amharic By Shek Mohammed Hamidin'}]}]



const filej = () => {
  return (
    <div>filej</div>
  )
}

export default filej